spring:
  application:
    name: e-comm-cart
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/postgres}
    username: ${DB_USER:my_user}
    password: ${DB_PASS:my_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

product-service:
  url: localhost:8081

server:
  port: 8082