version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: ecomm_cart
    environment:
      POSTGRES_DB: ecomm_cart
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
